### ISSUE TITLE
Structure XHTML parser should work on USCprelim

### ISSUE THREAD

**Issue by konklone** [unitedstates/uscode#1]
It might Just Work, since even though the styling is different, the HTML appears more or less the same, specifically the expcites:

http://uscode.house.gov/xhtml/uscprelim/PRELIMusc01.htm

If it does work, this is I think what the documentation should point to, rather than 2011. It's kept up to date much more quickly - the modified date for the file above is March 4, 2013.

It may take me a bit to test it out, as my Internet is sloppy this week, but this might just be close-able with a docs change.

**Comment by JoshData** [comment]
Yeah that makes sense, cool.

**Comment by konklone** [comment]
I've verified this works on the USCprelim, and I updated the script to default to it, and to make the filename regex match more flexible to accommodate it. I also updated the README.

Still to do: merge the downloading into the script, have it cache by default.
