### ISSUE TITLE
`./run structure` not working

### ISSUE THREAD

**Issue by mpertierra** [unitedstates/uscode#10]
I followed the installation instructions and tried running `./run structure title=26`, but got an empty array as output. Is this project no longer being maintained?

**Comment by JoshData** [comment]
I don't think anyone has used this repo for a long while. In the meantime, Congress has made some very wonderful improvements to how they publish the US Code in XML. So this repository is really due for a make-over.

Extracting the table-of-contents structure of the Code should be fairly straightforward starting from the XML at http://uscode.house.gov/download/download.shtml. (The folks who maintain that are great and we can get in touch with them if there are any questions.)

**Comment by mpertierra** [comment]
Thank you for you quick response! What approach could one take to convert the XML file to JSON?

**Comment by JoshData** [comment]
You will have to write a program to load the XML and walk through the nodes.
